package VIEW;

import VIEW.FrmUsuario;

/**
 *
 * @author ph757
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

   /**
    * Creates new form FrmTelaPrincipal
    */
   public FrmTelaPrincipal() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktop = new javax.swing.JDesktopPane();
      jLabel1 = new javax.swing.JLabel();
      lblUsuario = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      lblData = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      menCadastro = new javax.swing.JMenu();
      menCadastrarProduto = new javax.swing.JMenuItem();
      menCadastrarCliente = new javax.swing.JMenuItem();
      menCadastrarUsuario = new javax.swing.JMenuItem();
      menRelatorio = new javax.swing.JMenu();
      menRelatorioVendas = new javax.swing.JMenuItem();
      menOpcoes = new javax.swing.JMenu();
      menOpcoesSobre = new javax.swing.JMenuItem();
      menOpcoeSair = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Tela Principal");
      setName("Tela Principal"); // NOI18N
      setResizable(false);

      desktop.setBackground(new java.awt.Color(153, 153, 153));
      desktop.setFocusable(false);

      javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
      desktop.setLayout(desktopLayout);
      desktopLayout.setHorizontalGroup(
         desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 540, Short.MAX_VALUE)
      );
      desktopLayout.setVerticalGroup(
         desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 320, Short.MAX_VALUE)
      );

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
      jLabel1.setText("Usuário");

      lblUsuario.setText("jLabel2");

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel3.setText("Data");

      lblData.setText("jLabel4");

      menCadastro.setText("Cadastro");
      menCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      menCadastrarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
      menCadastrarProduto.setText("Produtos");
      menCadastro.add(menCadastrarProduto);

      menCadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
      menCadastrarCliente.setText("Clientes");
      menCadastro.add(menCadastrarCliente);

      menCadastrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
      menCadastrarUsuario.setText("Usuários");
      menCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menCadastrarUsuarioActionPerformed(evt);
         }
      });
      menCadastro.add(menCadastrarUsuario);

      jMenuBar1.add(menCadastro);

      menRelatorio.setText("Relatório");
      menRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      menRelatorioVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
      menRelatorioVendas.setText("Vendas");
      menRelatorio.add(menRelatorioVendas);

      jMenuBar1.add(menRelatorio);

      menOpcoes.setText("Opções");
      menOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      menOpcoesSobre.setText("Sobre");
      menOpcoes.add(menOpcoesSobre);

      menOpcoeSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
      menOpcoeSair.setText("Sair");
      menOpcoes.add(menOpcoeSair);

      jMenuBar1.add(menOpcoes);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabel1)
                  .addGap(40, 40, 40))
               .addGroup(layout.createSequentialGroup()
                  .addGap(10, 10, 10)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      setSize(new java.awt.Dimension(719, 380));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void menCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrarUsuarioActionPerformed
      FrmUsuario objfrmusuario = new FrmUsuario();
      objfrmusuario.setVisible(true);
      desktop.add(objfrmusuario);
   }//GEN-LAST:event_menCadastrarUsuarioActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrmTelaPrincipal().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktop;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JLabel lblData;
   private javax.swing.JLabel lblUsuario;
   private javax.swing.JMenuItem menCadastrarCliente;
   private javax.swing.JMenuItem menCadastrarProduto;
   private javax.swing.JMenuItem menCadastrarUsuario;
   private javax.swing.JMenu menCadastro;
   private javax.swing.JMenuItem menOpcoeSair;
   private javax.swing.JMenu menOpcoes;
   private javax.swing.JMenuItem menOpcoesSobre;
   private javax.swing.JMenu menRelatorio;
   private javax.swing.JMenuItem menRelatorioVendas;
   // End of variables declaration//GEN-END:variables
}
