package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ph757
 */
public class FrmUsuario extends javax.swing.JInternalFrame {

   /**
    * Creates new form FrmUsuario
    */
   public FrmUsuario() {
      initComponents();
      txtUsuNome.requestFocus();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      txtUsuNome = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtUsuLogin = new javax.swing.JTextField();
      txtUsuSenha = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      cmbUsuNivelAcesso = new javax.swing.JComboBox<>();
      btnUsuCadastrar = new javax.swing.JButton();
      txtUsuFone = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      btnUsuPesquisar = new javax.swing.JButton();
      btnUsuAlterar = new javax.swing.JButton();
      btnUsuDeletar = new javax.swing.JButton();
      jLabel7 = new javax.swing.JLabel();
      txtUsuId = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblUsuario = new javax.swing.JTable();

      setClosable(true);
      setIconifiable(true);
      setTitle("Usuários");
      setPreferredSize(new java.awt.Dimension(540, 341));
      setVisible(true);

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel1.setText("*Nome");

      txtUsuNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtUsuNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel2.setText("*Login");

      txtUsuLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtUsuLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

      txtUsuSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel3.setText("*Senha");

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel4.setText("*Nivel de Acesso");

      cmbUsuNivelAcesso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      cmbUsuNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Usuario" }));
      cmbUsuNivelAcesso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      btnUsuCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnUsuCadastrar.setText("Cadastrar");
      btnUsuCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnUsuCadastrar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUsuCadastrarActionPerformed(evt);
         }
      });

      txtUsuFone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel5.setText("Fone");

      jLabel6.setText("(*) Campos Obrigatórios");

      btnUsuPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnUsuPesquisar.setText("Pesquisar");
      btnUsuPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      btnUsuPesquisar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUsuPesquisarActionPerformed(evt);
         }
      });

      btnUsuAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnUsuAlterar.setText("Alterar");
      btnUsuAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      btnUsuDeletar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnUsuDeletar.setText("Deletar");
      btnUsuDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

      jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel7.setText("Id:");

      txtUsuId.setEditable(false);
      txtUsuId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtUsuId.setEnabled(false);

      tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPane1.setViewportView(tblUsuario);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel6)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabel7)
                     .addGap(18, 18, 18)
                     .addComponent(txtUsuId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                     .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtUsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(26, 26, 26)
                     .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                     .addComponent(txtUsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                     .addGap(8, 8, 8)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(btnUsuCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(30, 30, 30)
                           .addComponent(btnUsuPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(txtUsuFone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGap(18, 18, 18)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                           .addGap(0, 0, Short.MAX_VALUE)
                           .addComponent(btnUsuAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUsuDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbUsuNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(41, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel7)
               .addComponent(txtUsuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUsuFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cmbUsuNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnUsuCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnUsuPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnUsuAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnUsuDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(23, 23, 23))
      );

      setBounds(0, 0, 561, 422);
   }// </editor-fold>//GEN-END:initComponents

   private void btnUsuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuCadastrarActionPerformed
      cadastrar();
   }//GEN-LAST:event_btnUsuCadastrarActionPerformed

   private void btnUsuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuPesquisarActionPerformed
      listarValoresUsuario();
   }//GEN-LAST:event_btnUsuPesquisarActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnUsuAlterar;
   private javax.swing.JButton btnUsuCadastrar;
   private javax.swing.JButton btnUsuDeletar;
   private javax.swing.JButton btnUsuPesquisar;
   private javax.swing.JComboBox<String> cmbUsuNivelAcesso;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblUsuario;
   private javax.swing.JTextField txtUsuFone;
   private javax.swing.JTextField txtUsuId;
   private javax.swing.JTextField txtUsuLogin;
   private javax.swing.JTextField txtUsuNome;
   private javax.swing.JTextField txtUsuSenha;
   // End of variables declaration//GEN-END:variables

   private void cadastrar() {
      //Declara Variaveis para receber o resultado do usuario do form, depois passa o resultados para DTO e depois executa a classe DAO
      if (txtUsuNome.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Preencha Nome do Usuário");
         txtUsuNome.requestFocus();
      } else if (txtUsuLogin.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Preencha o Login");
         txtUsuLogin.requestFocus();
      } else if (txtUsuSenha.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Preencha a Senha");
         txtUsuSenha.requestFocus();
      } else if (cmbUsuNivelAcesso.getSelectedItem().equals("Selecione")) {
         JOptionPane.showMessageDialog(null, "Selecione o Nivel de Acesso");
      } else {
         String nome, login, senha, fone, nivelAcesso;
         nome = txtUsuNome.getText();
         login = txtUsuLogin.getText();
         senha = txtUsuSenha.getText();
         fone = txtUsuFone.getText();
         nivelAcesso = cmbUsuNivelAcesso.getSelectedItem().toString();

         //informações recebidas, agora passa para DTO encapsular os dados
         UsuarioDTO objusuariodto = new UsuarioDTO();

         objusuariodto.setNome(nome);
         objusuariodto.setLogin(login);
         objusuariodto.setSenha(senha);
         objusuariodto.setFone(fone);
         objusuariodto.setNivelDeAcesso(nivelAcesso);

         //Dados já passados para classe DTO agora executar o metodo da Classe DAO
         UsuarioDAO objusuariodao = new UsuarioDAO();
         objusuariodao.cadastrarUsuario(objusuariodto);
         JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso Numero: ");

         limparCampos();
      }
   }

   private void listarValoresUsuario() {

      UsuarioDAO objuUsuarioDAO = new UsuarioDAO();
      try {

         DefaultTableModel model = (DefaultTableModel) tblUsuario.getModel();
         model.setNumRows(0);

         ArrayList<UsuarioDTO> lista = objuUsuarioDAO.pesquisarUsuario();

         for (int i = 0; i < lista.size(); i++) {
            model.addRow(new Object[]{
               lista.get(i).getIdUser(),
               lista.get(i).getNome(),
               lista.get(i).getLogin(),
               lista.get(i).getSenha(),
               lista.get(i).getFone(),
               lista.get(i).getNivelDeAcesso()
            });
         }
      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "FrmUsuario - pesquisaeUsuario() " + e);
      }
   }

   private void limparCampos() {
      txtUsuNome.setText(null);
      txtUsuId.setText(null);
      txtUsuLogin.setText(null);
      txtUsuSenha.setText(null);
      txtUsuFone.setText(null);
      cmbUsuNivelAcesso.setSelectedIndex(0);
      txtUsuNome.requestFocus();
   }

}
