package VIEW;

import java.awt.Color;

/**
 *
 * @author ph757
 */
public class Menu extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form TelaPrincipal
     */
    public Menu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDinamico = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        lblIconLogo = new javax.swing.JLabel();
        panelCadastro = new javax.swing.JPanel();
        btnCadastrarUsuario = new javax.swing.JLabel();
        lblUsuarioLegenda = new javax.swing.JLabel();
        panelRelatorios = new javax.swing.JPanel();
        btnRelatorioVendas = new javax.swing.JLabel();
        lblVendasLegenda = new javax.swing.JLabel();
        panelOpcoes = new javax.swing.JPanel();
        btnOpcoesAjuda = new javax.swing.JLabel();
        btnOpcoesSobre = new javax.swing.JLabel();
        lblSobreLegenda = new javax.swing.JLabel();
        lblAjudaLegenda = new javax.swing.JLabel();
        panelLateralMenu = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JLabel();
        btnOpcoes = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        lblNomeUser = new javax.swing.JLabel();
        btnRelatorios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblIconFundoAzul = new javax.swing.JLabel();
        panelBarraSup = new javax.swing.JPanel();
        panelBtnClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        lblBarraSup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frameMenu"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDinamico.setBackground(new java.awt.Color(255, 255, 255));
        panelDinamico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo.setBackground(new java.awt.Color(255, 255, 255));
        panelLogo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        panelLogo.setMinimumSize(new java.awt.Dimension(520, 420));
        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconLogo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblIconLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconLogo.setText("LOGO");
        lblIconLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLogo.add(lblIconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 370, 330));

        panelDinamico.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        panelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        panelCadastro.setMinimumSize(new java.awt.Dimension(520, 420));
        panelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/adicionar-usuario.png"))); // NOI18N
        btnCadastrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarUsuarioMouseClicked(evt);
            }
        });
        panelCadastro.add(btnCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 110));

        lblUsuarioLegenda.setText("Usuário");
        panelCadastro.add(lblUsuarioLegenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        panelDinamico.add(panelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        panelRelatorios.setBackground(new java.awt.Color(255, 255, 255));
        panelRelatorios.setMinimumSize(new java.awt.Dimension(520, 420));
        panelRelatorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRelatorioVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/relatorios vendas.png"))); // NOI18N
        btnRelatorioVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorioVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorioVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioVendasMouseClicked(evt);
            }
        });
        panelRelatorios.add(btnRelatorioVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 110));

        lblVendasLegenda.setText("Vendas");
        panelRelatorios.add(lblVendasLegenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        panelDinamico.add(panelRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        panelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        panelOpcoes.setMinimumSize(new java.awt.Dimension(520, 420));
        panelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcoesAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOpcoesAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/help.png"))); // NOI18N
        btnOpcoesAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcoesAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelOpcoes.add(btnOpcoesAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 130, 110));

        btnOpcoesSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOpcoesSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/about.png"))); // NOI18N
        btnOpcoesSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcoesSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpcoesSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpcoesSobreMouseClicked(evt);
            }
        });
        panelOpcoes.add(btnOpcoesSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 110));

        lblSobreLegenda.setText("Sobre");
        panelOpcoes.add(lblSobreLegenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        lblAjudaLegenda.setText("Ajuda");
        panelOpcoes.add(lblAjudaLegenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        panelDinamico.add(panelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        getContentPane().add(panelDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 520, 420));

        panelLateralMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastro.setBackground(new java.awt.Color(153, 153, 153));
        btnCadastro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCadastro.setText("CADASTRO");
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroMouseExited(evt);
            }
        });
        panelLateralMenu.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 60));

        btnOpcoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpcoes.setForeground(new java.awt.Color(255, 255, 255));
        btnOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOpcoes.setText("OPÇÕES");
        btnOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpcoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOpcoesMouseExited(evt);
            }
        });
        panelLateralMenu.add(btnOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 60));

        lblIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icon user Azul.png"))); // NOI18N
        panelLateralMenu.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 80));

        lblNomeUser.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNomeUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeUser.setText("Usuário");
        panelLateralMenu.add(lblNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, -1));

        btnRelatorios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setText("RELATÓRIOS");
        btnRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseExited(evt);
            }
        });
        panelLateralMenu.add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        panelLateralMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 180, 10));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        panelLateralMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 10));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        panelLateralMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, 10));

        lblIconFundoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/fundo1.jpg"))); // NOI18N
        lblIconFundoAzul.setText("jLabel3");
        panelLateralMenu.add(lblIconFundoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));

        getContentPane().add(panelLateralMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));

        panelBarraSup.setBackground(new java.awt.Color(255, 255, 255));
        panelBarraSup.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        panelBarraSup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 480, 30));

        panelBtnClose.setBackground(new java.awt.Color(255, 255, 255));
        panelBtnClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("x");
        btnClose.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        panelBtnClose.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 30));

        lblBarraSup.setBackground(new java.awt.Color(255, 255, 255));
        lblBarraSup.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblBarraSup.setForeground(new java.awt.Color(255, 255, 255));
        lblBarraSup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraSupMouseDragged(evt);
            }
        });
        lblBarraSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBarraSupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBarraSupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraSupMousePressed(evt);
            }
        });
        panelBtnClose.add(lblBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

        getContentPane().add(panelBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(760, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private void lblBarraSupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
   }//GEN-LAST:event_lblBarraSupMousePressed
   private void lblBarraSupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
   }//GEN-LAST:event_lblBarraSupMouseDragged
   private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
   }//GEN-LAST:event_btnCloseMouseClicked
   private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(new Color(255, 4, 0));
   }//GEN-LAST:event_btnCloseMouseEntered

   private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setBackground(Color.white);
   }//GEN-LAST:event_btnCloseMouseExited

   private void lblBarraSupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseEntered
        panelBarraSup.setBackground(new Color(204, 204, 204));
   }//GEN-LAST:event_lblBarraSupMouseEntered

   private void lblBarraSupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseExited
        panelBarraSup.setBackground(Color.white);
   }//GEN-LAST:event_lblBarraSupMouseExited

   private void btnCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseEntered
        btnCadastro.setOpaque(true);
        btnCadastro.setBackground(new Color(7, 37, 156, 120));
        repaint();
        panelDinamico.setComponentZOrder(panelCadastro, 0);
   }//GEN-LAST:event_btnCadastroMouseEntered

   private void btnCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseExited
        btnCadastro.setBackground(new Color(0, 0, 0, 1));
        repaint();//Evita Flag no Componente
   }//GEN-LAST:event_btnCadastroMouseExited

   private void btnRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseEntered
        btnRelatorios.setOpaque(true);
        btnRelatorios.setBackground(new Color(7, 37, 156, 120));
        repaint();
        panelDinamico.setComponentZOrder(panelRelatorios, 0);
   }//GEN-LAST:event_btnRelatoriosMouseEntered

   private void btnRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseExited
        btnRelatorios.setBackground(new Color(0, 0, 0, 0));
        repaint();//Evita Flag no Componente
   }//GEN-LAST:event_btnRelatoriosMouseExited

   private void btnOpcoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcoesMouseEntered
        btnOpcoes.setOpaque(true);
        btnOpcoes.setBackground(new Color(7, 37, 156, 120));
        repaint();
        panelDinamico.setComponentZOrder(panelOpcoes, 0);

   }//GEN-LAST:event_btnOpcoesMouseEntered

   private void btnOpcoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcoesMouseExited
        btnOpcoes.setBackground(new Color(0, 0, 0, 1));
        repaint(); //Evita Flag no Componente
   }//GEN-LAST:event_btnOpcoesMouseExited

    private void btnOpcoesSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcoesSobreMouseClicked
        new TelaOpcoesSobre().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOpcoesSobreMouseClicked

    private void btnRelatorioVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioVendasMouseClicked
        new TelaRelatorioVendas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRelatorioVendasMouseClicked

    private void btnCadastrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioMouseClicked
        new TelaCadastroUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                  .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                  .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                  .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                  .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCadastrarUsuario;
    private javax.swing.JLabel btnCadastro;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnOpcoes;
    private javax.swing.JLabel btnOpcoesAjuda;
    private javax.swing.JLabel btnOpcoesSobre;
    private javax.swing.JLabel btnRelatorioVendas;
    private javax.swing.JLabel btnRelatorios;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAjudaLegenda;
    private javax.swing.JLabel lblBarraSup;
    private javax.swing.JLabel lblIconFundoAzul;
    public javax.swing.JLabel lblIconLogo;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblNomeUser;
    private javax.swing.JLabel lblSobreLegenda;
    private javax.swing.JLabel lblUsuarioLegenda;
    private javax.swing.JLabel lblVendasLegenda;
    private javax.swing.JPanel panelBarraSup;
    private javax.swing.JPanel panelBtnClose;
    private javax.swing.JPanel panelCadastro;
    public static javax.swing.JPanel panelDinamico;
    private javax.swing.JPanel panelLateralMenu;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelOpcoes;
    private javax.swing.JPanel panelRelatorios;
    // End of variables declaration//GEN-END:variables

}
