/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ph757
 */
public class TelaLogin extends javax.swing.JFrame {

   int xMouse, yMouse;

   /**
    * Creates new form TelaLogin
    */
   public TelaLogin() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      pnFundo = new javax.swing.JPanel();
      panBtnClose = new javax.swing.JPanel();
      lblClose = new javax.swing.JLabel();
      lblBarraSup = new javax.swing.JLabel();
      lblNomeEmpresa = new javax.swing.JLabel();
      lblIconUser = new javax.swing.JLabel();
      lblIniciarSessao = new javax.swing.JLabel();
      lblFundoLado = new javax.swing.JLabel();
      txtLogUsuario = new javax.swing.JTextField();
      sepUsuario = new javax.swing.JSeparator();
      lblUsuario = new javax.swing.JLabel();
      lblSenha = new javax.swing.JLabel();
      sepSenha = new javax.swing.JSeparator();
      lblBemVindo = new javax.swing.JLabel();
      txtLogSenha = new javax.swing.JPasswordField();
      panBtnLogar = new javax.swing.JPanel();
      lblLogar = new javax.swing.JLabel();
      sepBemVindo = new javax.swing.JSeparator();
      panBarraSup = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setUndecorated(true);
      setResizable(false);
      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      pnFundo.setBackground(new java.awt.Color(255, 255, 255));
      pnFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      panBtnClose.setBackground(new java.awt.Color(255, 255, 255));
      panBtnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

      lblClose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblClose.setText("x");
      lblClose.setToolTipText("Fechar");
      lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            lblCloseMouseClicked(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            lblCloseMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            lblCloseMouseEntered(evt);
         }
      });

      javax.swing.GroupLayout panBtnCloseLayout = new javax.swing.GroupLayout(panBtnClose);
      panBtnClose.setLayout(panBtnCloseLayout);
      panBtnCloseLayout.setHorizontalGroup(
         panBtnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnCloseLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      panBtnCloseLayout.setVerticalGroup(
         panBtnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnCloseLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pnFundo.add(panBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 30));

      lblBarraSup.setBackground(new java.awt.Color(255, 255, 255));
      lblBarraSup.setToolTipText("Arrastar Janela");
      lblBarraSup.setMaximumSize(new java.awt.Dimension(100, 100));
      lblBarraSup.setMinimumSize(new java.awt.Dimension(100, 100));
      lblBarraSup.setPreferredSize(new java.awt.Dimension(100, 100));
      lblBarraSup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
         public void mouseDragged(java.awt.event.MouseEvent evt) {
            lblBarraSupMouseDragged(evt);
         }
      });
      lblBarraSup.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lblBarraSupMousePressed(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            lblBarraSupMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            lblBarraSupMouseEntered(evt);
         }
      });
      pnFundo.add(lblBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

      lblNomeEmpresa.setBackground(new java.awt.Color(255, 255, 255));
      lblNomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
      lblNomeEmpresa.setForeground(new java.awt.Color(255, 255, 255));
      lblNomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblNomeEmpresa.setText("EMPRESA X7");
      pnFundo.add(lblNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 30));

      lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/user2.png"))); // NOI18N
      pnFundo.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

      lblIniciarSessao.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
      lblIniciarSessao.setForeground(new java.awt.Color(255, 255, 255));
      lblIniciarSessao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblIniciarSessao.setText("Iniciar Sessão");
      pnFundo.add(lblIniciarSessao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, 50));

      lblFundoLado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/fundo1.jpg"))); // NOI18N
      pnFundo.add(lblFundoLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 380));

      txtLogUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
      txtLogUsuario.setBorder(null);
      txtLogUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      txtLogUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            txtLogUsuarioMousePressed(evt);
         }
      });
      pnFundo.add(txtLogUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 350, 30));
      pnFundo.add(sepUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 350, 30));

      lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      lblUsuario.setText("USUÁRIO");
      pnFundo.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

      lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      lblSenha.setText("SENHA");
      pnFundo.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));
      pnFundo.add(sepSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 350, 30));

      lblBemVindo.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
      lblBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblBemVindo.setText("BEM-VINDO");
      pnFundo.add(lblBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 420, -1));

      txtLogSenha.setForeground(new java.awt.Color(153, 153, 153));
      txtLogSenha.setText("Field");
      txtLogSenha.setBorder(null);
      txtLogSenha.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            txtLogSenhaMousePressed(evt);
         }
      });
      pnFundo.add(txtLogSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 350, 30));

      panBtnLogar.setBackground(new java.awt.Color(9, 22, 39));

      lblLogar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
      lblLogar.setForeground(new java.awt.Color(255, 255, 255));
      lblLogar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblLogar.setText("Entrar");
      lblLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      lblLogar.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseExited(java.awt.event.MouseEvent evt) {
            lblLogarMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            lblLogarMouseEntered(evt);
         }
      });

      javax.swing.GroupLayout panBtnLogarLayout = new javax.swing.GroupLayout(panBtnLogar);
      panBtnLogar.setLayout(panBtnLogarLayout);
      panBtnLogarLayout.setHorizontalGroup(
         panBtnLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnLogarLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      panBtnLogarLayout.setVerticalGroup(
         panBtnLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBtnLogarLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pnFundo.add(panBtnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 130, 40));
      pnFundo.add(sepBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 180, 20));

      panBarraSup.setBackground(new java.awt.Color(255, 255, 255));

      javax.swing.GroupLayout panBarraSupLayout = new javax.swing.GroupLayout(panBarraSup);
      panBarraSup.setLayout(panBarraSupLayout);
      panBarraSupLayout.setHorizontalGroup(
         panBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 380, Short.MAX_VALUE)
      );
      panBarraSupLayout.setVerticalGroup(
         panBarraSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 30, Short.MAX_VALUE)
      );

      pnFundo.add(panBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 380, 30));

      getContentPane().add(pnFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

      setSize(new java.awt.Dimension(682, 381));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
      //Quando o Mouse Entrar Na área de um componente
      //neste caso quando entrar na area do x para fechar a janela o label ficara vermelho
      panBtnClose.setBackground(Color.red);
   }//GEN-LAST:event_lblCloseMouseEntered

   private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
      //Disparado quando o mouse sai da área de um componente.
      panBtnClose.setBackground(Color.white);
   }//GEN-LAST:event_lblCloseMouseExited

   private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
      //Disparado quando o botão do mouse é clicado (pressionado e liberado) em um componente.
      System.exit(0);
   }//GEN-LAST:event_lblCloseMouseClicked

   private void lblBarraSupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMousePressed
      xMouse = evt.getX();
      yMouse = evt.getY();
   }//GEN-LAST:event_lblBarraSupMousePressed

   private void lblBarraSupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseDragged
      int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x - xMouse, y - yMouse);
   }//GEN-LAST:event_lblBarraSupMouseDragged

   private void lblBarraSupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseEntered

      panBarraSup.setBackground(new Color(204, 204, 204));
   }//GEN-LAST:event_lblBarraSupMouseEntered

   private void lblBarraSupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseExited
      panBarraSup.setBackground(new Color(255, 255, 255));
   }//GEN-LAST:event_lblBarraSupMouseExited

   private void lblLogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogarMouseEntered
      panBtnLogar.setBackground(new Color(39, 54, 86));
   }//GEN-LAST:event_lblLogarMouseEntered

   private void lblLogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogarMouseExited
      panBtnLogar.setBackground(new Color(9, 22, 39));
   }//GEN-LAST:event_lblLogarMouseExited

   private void txtLogSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogSenhaMousePressed
      if (txtLogUsuario.getText().isEmpty()) {
         txtLogUsuario.setText("Digite o Nome de Usuário");
         txtLogUsuario.setForeground(new Color(153, 153, 153));
      }
      txtLogSenha.setText(null);
      txtLogSenha.setForeground(new Color(0, 0, 0));
   }//GEN-LAST:event_txtLogSenhaMousePressed

   private void txtLogUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogUsuarioMousePressed
      if (txtLogUsuario.getText().equals("Digite o Nome de Usuário")) {
         txtLogUsuario.setText(null);
      }

      if (String.valueOf(txtLogSenha.getPassword()).isEmpty()) {
         txtLogSenha.setText("*****");
         txtLogSenha.setForeground(new Color(153, 153, 153));
      }

   }//GEN-LAST:event_txtLogUsuarioMousePressed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new TelaLogin().setVisible(true);
         }

      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel lblBarraSup;
   private javax.swing.JLabel lblBemVindo;
   private javax.swing.JLabel lblClose;
   private javax.swing.JLabel lblFundoLado;
   private javax.swing.JLabel lblIconUser;
   private javax.swing.JLabel lblIniciarSessao;
   private javax.swing.JLabel lblLogar;
   private javax.swing.JLabel lblNomeEmpresa;
   private javax.swing.JLabel lblSenha;
   private javax.swing.JLabel lblUsuario;
   private javax.swing.JPanel panBarraSup;
   private javax.swing.JPanel panBtnClose;
   private javax.swing.JPanel panBtnLogar;
   private javax.swing.JPanel pnFundo;
   private javax.swing.JSeparator sepBemVindo;
   private javax.swing.JSeparator sepSenha;
   private javax.swing.JSeparator sepUsuario;
   private javax.swing.JPasswordField txtLogSenha;
   private javax.swing.JTextField txtLogUsuario;
   // End of variables declaration//GEN-END:variables

   private void logar() {
      try {
         String login, senha;

         login = txtLogUsuario.getText();
         senha = new String(txtLogSenha.getPassword());

         UsuarioDTO objUsuarioDto = new UsuarioDTO();
         objUsuarioDto.setLogin(login);
         objUsuarioDto.setSenha(senha);
         UsuarioDAO objUsuarioDao = new UsuarioDAO();
         ResultSet rsUsuarioDao = objUsuarioDao.autenticacaoUsuario(objUsuarioDto);

         if (rsUsuarioDao.next()) {
            String perfil = rsUsuarioDao.getString(4);
            FrmTelaPrincipal telaPrincipal = new FrmTelaPrincipal();

            if (perfil.equals("Administrador")) {
               telaPrincipal.setVisible(true);
               dispose();
            } else {
               telaPrincipal.setVisible(true);
               dispose();
            }
         } else {
            JOptionPane.showMessageDialog(null, "UsuÃ¡rio ou Senha Incorreto");
         }
      } catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "VIEW/btnLoginEntrar: " + e);
      }
   }

}
