/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Color;

/**
 *
 * @author ph757
 */
public class TelaPrincipal extends javax.swing.JFrame {

   int xMouse, yMouse;

   /**
    * Creates new form TelaPrincipal
    */
   public TelaPrincipal() {
      initComponents();
      panCadastro.setBackground(new Color(0, 0, 0, 0));
      panRelatorios.setBackground(new Color(0, 0, 0, 0));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      panPrincipal = new javax.swing.JPanel();
      lblBarraSup = new javax.swing.JLabel();
      btnOpcoes = new javax.swing.JLabel();
      lblIconUser = new javax.swing.JLabel();
      lblNomeUser = new javax.swing.JLabel();
      btnRelatorios = new javax.swing.JLabel();
      jSeparator1 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();
      jSeparator3 = new javax.swing.JSeparator();
      panRelatorios = new javax.swing.JPanel();
      panOpcoes = new javax.swing.JPanel();
      panCadastro = new javax.swing.JPanel();
      btnCadastro = new javax.swing.JLabel();
      lblIconFundoAzul = new javax.swing.JLabel();
      panBarraSup = new javax.swing.JPanel();
      panBtnClose = new javax.swing.JPanel();
      lblBtnClose = new javax.swing.JLabel();
      lblIconLogo = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Tela Principal");
      setBackground(new java.awt.Color(255, 255, 255));
      setUndecorated(true);
      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
      panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      lblBarraSup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
         public void mouseDragged(java.awt.event.MouseEvent evt) {
            lblBarraSupMouseDragged(evt);
         }
      });
      lblBarraSup.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mousePressed(java.awt.event.MouseEvent evt) {
            lblBarraSupMousePressed(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            lblBarraSupMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            lblBarraSupMouseEntered(evt);
         }
      });
      panPrincipal.add(lblBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

      btnOpcoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      btnOpcoes.setForeground(new java.awt.Color(255, 255, 255));
      btnOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      btnOpcoes.setText("OPÇÕES");
      panPrincipal.add(btnOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 60));

      lblIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icon user Azul.png"))); // NOI18N
      panPrincipal.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 80));

      lblNomeUser.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
      lblNomeUser.setForeground(new java.awt.Color(255, 255, 255));
      lblNomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblNomeUser.setText("Usuário");
      panPrincipal.add(lblNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, -1));

      btnRelatorios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
      btnRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      btnRelatorios.setText("RELATÓRIOS");
      btnRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseExited(java.awt.event.MouseEvent evt) {
            btnRelatoriosMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnRelatoriosMouseEntered(evt);
         }
      });
      panPrincipal.add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

      jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
      jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
      panPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 180, 10));

      jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
      jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
      panPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 10));

      jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
      jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
      panPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, 10));

      panRelatorios.setBackground(new java.awt.Color(102, 102, 102));
      panRelatorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
      panPrincipal.add(panRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

      panOpcoes.setBackground(new java.awt.Color(102, 102, 102));
      panOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseExited(java.awt.event.MouseEvent evt) {
            panOpcoesMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            panOpcoesMouseEntered(evt);
         }
      });
      panOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
      panPrincipal.add(panOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 60));

      panCadastro.setBackground(new java.awt.Color(102, 102, 102));
      panCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      btnCadastro.setBackground(new java.awt.Color(153, 153, 153));
      btnCadastro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
      btnCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      btnCadastro.setText("CADASTRO");
      btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseExited(java.awt.event.MouseEvent evt) {
            btnCadastroMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnCadastroMouseEntered(evt);
         }
      });
      panCadastro.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 60));

      panPrincipal.add(panCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 60));

      lblIconFundoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/fundo1.jpg"))); // NOI18N
      lblIconFundoAzul.setText("jLabel3");
      panPrincipal.add(lblIconFundoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));

      panBarraSup.setBackground(new java.awt.Color(255, 255, 255));
      panPrincipal.add(panBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 480, 30));

      panBtnClose.setBackground(new java.awt.Color(255, 255, 255));
      panBtnClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      lblBtnClose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      lblBtnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblBtnClose.setText("x");
      lblBtnClose.setVerticalAlignment(javax.swing.SwingConstants.TOP);
      lblBtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      lblBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            lblBtnCloseMouseClicked(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            lblBtnCloseMouseExited(evt);
         }
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            lblBtnCloseMouseEntered(evt);
         }
      });
      panBtnClose.add(lblBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

      panPrincipal.add(panBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 30));

      lblIconLogo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
      lblIconLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblIconLogo.setText("LOGO");
      lblIconLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      panPrincipal.add(lblIconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 340, 310));

      getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 450));

      setSize(new java.awt.Dimension(760, 450));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void lblBarraSupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMousePressed
      xMouse = evt.getX();
      yMouse = evt.getY();
   }//GEN-LAST:event_lblBarraSupMousePressed

   private void lblBarraSupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseDragged
      int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x - xMouse, y - yMouse);
   }//GEN-LAST:event_lblBarraSupMouseDragged

   private void lblBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCloseMouseClicked
      System.exit(0);
   }//GEN-LAST:event_lblBtnCloseMouseClicked

   private void lblBtnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCloseMouseEntered
      panBtnClose.setBackground(Color.red);
   }//GEN-LAST:event_lblBtnCloseMouseEntered

   private void lblBtnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCloseMouseExited
      panBtnClose.setBackground(Color.white);
   }//GEN-LAST:event_lblBtnCloseMouseExited

   private void lblBarraSupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseEntered
      panBarraSup.setBackground(new Color(204, 204, 204));
   }//GEN-LAST:event_lblBarraSupMouseEntered

   private void lblBarraSupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraSupMouseExited
      panBarraSup.setBackground(Color.white);
   }//GEN-LAST:event_lblBarraSupMouseExited

   private void btnCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseEntered

      panCadastro.setOpaque(true);
      panCadastro.setBackground(new Color(7, 37, 156, 120));
      repaint(); //Resolveu Problema de primeiro frame com Problema trazendo imagem estranha
   }//GEN-LAST:event_btnCadastroMouseEntered

   private void btnCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseExited
      panCadastro.setOpaque(false);
      panCadastro.setBackground(new Color(0, 0, 0, 1));
   }//GEN-LAST:event_btnCadastroMouseExited

   private void btnRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseEntered

      panRelatorios.setOpaque(true);
      panRelatorios.setBackground(new Color(7, 37, 156, 120));
      repaint();
   }//GEN-LAST:event_btnRelatoriosMouseEntered

   private void btnRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseExited
      panRelatorios.setOpaque(false);
      panRelatorios.setBackground(new Color(0, 0, 0, 1));
   }//GEN-LAST:event_btnRelatoriosMouseExited

   private void panOpcoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panOpcoesMouseEntered
      panOpcoes.setOpaque(true);
      panOpcoes.setBackground(new Color(7, 37, 156, 120));
      repaint();
   }//GEN-LAST:event_panOpcoesMouseEntered

   private void panOpcoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panOpcoesMouseExited
      panOpcoes.setOpaque(false);
      panOpcoes.setBackground(new Color(0, 0, 0, 1));
   }//GEN-LAST:event_panOpcoesMouseExited

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new TelaPrincipal().setVisible(true);
         }

      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel btnCadastro;
   private javax.swing.JLabel btnOpcoes;
   private javax.swing.JLabel btnRelatorios;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JLabel lblBarraSup;
   private javax.swing.JLabel lblBtnClose;
   private javax.swing.JLabel lblIconFundoAzul;
   private javax.swing.JLabel lblIconLogo;
   private javax.swing.JLabel lblIconUser;
   private javax.swing.JLabel lblNomeUser;
   private javax.swing.JPanel panBarraSup;
   private javax.swing.JPanel panBtnClose;
   private javax.swing.JPanel panCadastro;
   private javax.swing.JPanel panOpcoes;
   private javax.swing.JPanel panPrincipal;
   private javax.swing.JPanel panRelatorios;
   // End of variables declaration//GEN-END:variables
}
